In [1]:
import numpy as np

In [2]:
arr3d = np.arange (50). reshape(2,5,5)
arr3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]],

       [[25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])

In [3]:
arr3d[1,2,3]

38

In [4]:
arr3d[0,3,4]

19

In [5]:
arr3d[1,3]

array([40, 41, 42, 43, 44])

In [6]:
arr3d[0,2:,4:]

array([[14],
       [19],
       [24]])

In [7]:
arr3d[1,2:,1:3]

array([[36, 37],
       [41, 42],
       [46, 47]])

In [8]:
arr3d[0,2:4,4]

array([14, 19])

In [9]:
arr3d[0:1,2:,4:]

array([[[14],
        [19],
        [24]]])

In [10]:
arr3d[0:1,2:,4]

array([[14, 19, 24]])

In [11]:
arr3d[0:,0:,0:1]

array([[[ 0],
        [ 5],
        [10],
        [15],
        [20]],

       [[25],
        [30],
        [35],
        [40],
        [45]]])

In [12]:
arr3d[0:,0:,0]

array([[ 0,  5, 10, 15, 20],
       [25, 30, 35, 40, 45]])

In [13]:
import pandas as pd

In [14]:
obj = pd.Series([1,2,3,4])

In [15]:
obj

0    1
1    2
2    3
3    4
dtype: int64

In [16]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [17]:
obj.values

array([1, 2, 3, 4], dtype=int64)

In [18]:
obj1 = pd.Series([13,25,56,85],index = ['a','b','c','d'])

In [19]:
obj1

a    13
b    25
c    56
d    85
dtype: int64

In [20]:
obj1['c'] = 100

In [21]:
obj1

a     13
b     25
c    100
d     85
dtype: int64

In [22]:
del obj1['c']

In [23]:
obj1

a    13
b    25
d    85
dtype: int64

In [24]:
obj1['z'] = 111

In [25]:
obj1

a     13
b     25
d     85
z    111
dtype: int64

In [26]:
index=[1,2,3,4,5]

In [27]:
obj2 =pd.Series(["apple","orange","mango","red","yellow"],index)

In [28]:
obj2

1     apple
2    orange
3     mango
4       red
5    yellow
dtype: object

In [29]:
obj2[2]

'orange'

In [30]:
obj2[[3,5,1]]

3     mango
5    yellow
1     apple
dtype: object

In [31]:
obj2[obj2=="orange"]

2    orange
dtype: object

In [32]:
obj2*2

1      appleapple
2    orangeorange
3      mangomango
4          redred
5    yellowyellow
dtype: object

In [33]:
print("apple"*5)

appleappleappleappleapple


In [34]:
s1 =pd.Series([100,200,300,400,500,], index =["hy","by","2h","3h","5h"])

In [35]:
s1

hy    100
by    200
2h    300
3h    400
5h    500
dtype: int64

In [36]:
"4h" in s1

False

In [37]:
"5h" in s1

True

# creating a series using python dictionary

In [38]:
sdata ={'ohio': 3500, 'texas':7100, 'oregon':1600,'utah':5000}

In [39]:
s2=pd.Series(sdata)

In [40]:
s2

ohio      3500
texas     7100
oregon    1600
utah      5000
dtype: int64

In [41]:
states = ['california','ohio','oregon','texas']

In [42]:
s2 = pd.Series(sdata,index=states)

In [43]:
s2

california       NaN
ohio          3500.0
oregon        1600.0
texas         7100.0
dtype: float64

In [44]:
s2[pd.isnull(s2)]

california   NaN
dtype: float64

# data frames

In [45]:
data1 = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003],
 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [48]:
df = pd.DataFrame(data1)

In [49]:
df

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [50]:
pd.DataFrame(df, columns=['years','state','pop'])

years   state  pop
0    NaN    Ohio  1.5
1    NaN    Ohio  1.7
2    NaN    Ohio  3.6
3    NaN  Nevada  2.4
4    NaN  Nevada  2.9
5    NaN  Nevada  3.2

In [51]:
frame2 = pd.DataFrame(data1,columns =['year','state','pop','debt'],
index=['one','two','three','four','five','six'])

In [52]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [53]:
frame2['debt']=[100,50,56,75,46,87]

In [54]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   100
two    2001    Ohio  1.7    50
three  2002    Ohio  3.6    56
four   2001  Nevada  2.4    75
five   2002  Nevada  2.9    46
six    2003  Nevada  3.2    87

In [55]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [56]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [57]:
frame2[['state','year']]

state  year
one      Ohio  2000
two      Ohio  2001
three    Ohio  2002
four   Nevada  2001
five   Nevada  2002
six    Nevada  2003

In [58]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt       56
Name: three, dtype: object

In [59]:
frame2.iloc[2]

year     2002
state    Ohio
pop       3.6
debt       56
Name: three, dtype: object

In [60]:
 val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])


In [61]:
frame2['debt'] = val

In [62]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [63]:
frame2.debt['one','three','six']=[5,10,6]

F:\anaconda\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
F:\anaconda\lib\site-packages\pandas\core\indexing.py:190: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._setitem_with_indexer(indexer, value)


In [64]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   5.0
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6  10.0
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   6.0

In [65]:
frame2['eastern']=frame2.state == 'Ohio'

In [66]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   5.0     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6  10.0     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   6.0    False

In [67]:
mine = {'students':['asim','muzammil','daniyal','ahsan','yasir'],
      'passing year':[2017,2017,2017,2017,2017],
      'ssc marks':[660,670,681,698,680],
      'hsc marks':[650,671,640,760,737]}

In [68]:
mine1 = pd.DataFrame(mine)

In [69]:
mine1

students  passing year  ssc marks  hsc marks
0      asim          2017        660        650
1  muzammil          2017        670        671
2   daniyal          2017        681        640
3     ahsan          2017        698        760
4     yasir          2017        680        737

In [70]:
mine1['Total']= mine1['ssc marks'] + mine1['hsc marks']

In [71]:
mine1

students  passing year  ssc marks  hsc marks  Total
0      asim          2017        660        650   1310
1  muzammil          2017        670        671   1341
2   daniyal          2017        681        640   1321
3     ahsan          2017        698        760   1458
4     yasir          2017        680        737   1417

In [72]:
mine1 ['percentage'] = mine1['Total']*100 / 1950

In [73]:
mine1

students  passing year  ssc marks  hsc marks  Total  percentage
0      asim          2017        660        650   1310   67.179487
1  muzammil          2017        670        671   1341   68.769231
2   daniyal          2017        681        640   1321   67.743590
3     ahsan          2017        698        760   1458   74.769231
4     yasir          2017        680        737   1417   72.666667

In [74]:
mine1['Status']='null'

In [75]:
mine1

students  passing year  ssc marks  hsc marks  Total  percentage Status
0      asim          2017        660        650   1310   67.179487   null
1  muzammil          2017        670        671   1341   68.769231   null
2   daniyal          2017        681        640   1321   67.743590   null
3     ahsan          2017        698        760   1458   74.769231   null
4     yasir          2017        680        737   1417   72.666667   null

In [78]:
mine1['Status']= ['pass' if i >= 1400 else "fail" for i in mine1['Total']]

In [79]:
mine1

students  passing year  ssc marks  hsc marks  Total  percentage Status
0      asim          2017        660        650   1310   67.179487   fail
1  muzammil          2017        670        671   1341   68.769231   fail
2   daniyal          2017        681        640   1321   67.743590   fail
3     ahsan          2017        698        760   1458   74.769231   pass
4     yasir          2017        680        737   1417   72.666667   pass