# Boolean indexing

In [1]:
import numpy as np

In [2]:
names=np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])

In [3]:
data=np.random.randn(7,4)

In [4]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [6]:
data

array([[ 0.2179024 ,  0.70359678, -0.29098558,  1.34407768],
       [ 0.38333606,  1.2640083 ,  1.12732716,  1.1437134 ],
       [-0.04647485, -0.64520261,  0.73219239, -0.68192815],
       [-0.30933053,  0.69391551,  1.01814469,  0.11810554],
       [ 0.02704996, -1.01037421, -0.40373941, -0.8391421 ],
       [-0.74333054, -0.16094984,  1.7031448 ,  0.41338627],
       [ 0.11672293, -0.29734917,  1.39473826, -0.46649681]])

In [7]:
names=='Bob'

array([ True, False, False,  True, False, False, False])

In [8]:
data[names=='Bob']

array([[ 0.2179024 ,  0.70359678, -0.29098558,  1.34407768],
       [-0.30933053,  0.69391551,  1.01814469,  0.11810554]])

In [9]:
data[names !='Bob']

array([[ 0.38333606,  1.2640083 ,  1.12732716,  1.1437134 ],
       [-0.04647485, -0.64520261,  0.73219239, -0.68192815],
       [ 0.02704996, -1.01037421, -0.40373941, -0.8391421 ],
       [-0.74333054, -0.16094984,  1.7031448 ,  0.41338627],
       [ 0.11672293, -0.29734917,  1.39473826, -0.46649681]])

In [16]:
data[names=='Bob',1:3]

array([[ 0.70359678, -0.29098558],
       [ 0.69391551,  1.01814469]])

In [17]:
data

array([[ 0.2179024 ,  0.70359678, -0.29098558,  1.34407768],
       [ 0.38333606,  1.2640083 ,  1.12732716,  1.1437134 ],
       [-0.04647485, -0.64520261,  0.73219239, -0.68192815],
       [-0.30933053,  0.69391551,  1.01814469,  0.11810554],
       [ 0.02704996, -1.01037421, -0.40373941, -0.8391421 ],
       [-0.74333054, -0.16094984,  1.7031448 ,  0.41338627],
       [ 0.11672293, -0.29734917,  1.39473826, -0.46649681]])

In [20]:
data[3]

array([-0.30933053,  0.69391551,  1.01814469,  0.11810554])

In [21]:
data[[3,4,0,1]]

array([[-0.30933053,  0.69391551,  1.01814469,  0.11810554],
       [ 0.02704996, -1.01037421, -0.40373941, -0.8391421 ],
       [ 0.2179024 ,  0.70359678, -0.29098558,  1.34407768],
       [ 0.38333606,  1.2640083 ,  1.12732716,  1.1437134 ]])

In [23]:
cond = names == 'Bob'

In [24]:
data[~cond]

array([[ 0.38333606,  1.2640083 ,  1.12732716,  1.1437134 ],
       [-0.04647485, -0.64520261,  0.73219239, -0.68192815],
       [ 0.02704996, -1.01037421, -0.40373941, -0.8391421 ],
       [-0.74333054, -0.16094984,  1.7031448 ,  0.41338627],
       [ 0.11672293, -0.29734917,  1.39473826, -0.46649681]])

In [25]:
mask=(names =='Bob')|(names =='Will')

In [26]:
mask

array([ True, False,  True,  True,  True, False, False])

In [28]:
data[mask]

array([[ 0.2179024 ,  0.70359678, -0.29098558,  1.34407768],
       [-0.04647485, -0.64520261,  0.73219239, -0.68192815],
       [-0.30933053,  0.69391551,  1.01814469,  0.11810554],
       [ 0.02704996, -1.01037421, -0.40373941, -0.8391421 ]])

In [30]:
data<0

array([[False, False,  True, False],
       [False, False, False, False],
       [ True,  True, False,  True],
       [ True, False, False, False],
       [False,  True,  True,  True],
       [ True,  True, False, False],
       [False,  True, False,  True]])

In [31]:
data[data<0]

array([-0.29098558, -0.04647485, -0.64520261, -0.68192815, -0.30933053,
       -1.01037421, -0.40373941, -0.8391421 , -0.74333054, -0.16094984,
       -0.29734917, -0.46649681])

In [32]:
data[data<0] = 0

In [33]:
data

array([[0.2179024 , 0.70359678, 0.        , 1.34407768],
       [0.38333606, 1.2640083 , 1.12732716, 1.1437134 ],
       [0.        , 0.        , 0.73219239, 0.        ],
       [0.        , 0.69391551, 1.01814469, 0.11810554],
       [0.02704996, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 1.7031448 , 0.41338627],
       [0.11672293, 0.        , 1.39473826, 0.        ]])

# Fancy Indexing

In [34]:
arr = np.empty((8, 4))

In [35]:
for i in range(8):
    arr[i] =i

In [36]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [37]:
arr[4]

array([4., 4., 4., 4.])

In [38]:
arr[[4,6]]

array([[4., 4., 4., 4.],
       [6., 6., 6., 6.]])

In [39]:
arr[[4,6],2:]

array([[4., 4.],
       [6., 6.]])

In [40]:
 arr = np.arange(32).reshape((8, 4))

In [41]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [42]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [43]:
arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

# Transposing Arrays and Swapping Axes

In [44]:
arr = np.arange(15).reshape((3, 5))


In [45]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [46]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

# Universal Functions: Fast Element-Wise Array
Functions


In [48]:
arr = np.arange(10)

In [49]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [51]:
arr = np.random.randn(7) * 5

In [52]:
arr

array([ 6.62062304, -6.40618253,  2.71962782, -4.98895059, -1.63276707,
        5.71991432,  7.87098537])

In [53]:
remainder, whole_part = np.modf(arr)

In [54]:
remainder

array([ 0.62062304, -0.40618253,  0.71962782, -0.98895059, -0.63276707,
        0.71991432,  0.87098537])

In [56]:
whole_part

array([ 6., -6.,  2., -4., -1.,  5.,  7.])

# Array-Oriented Programming with Arrays

In [65]:
names = ['muzammil','hutiya','hai','yasir','genious','hai','muzammil']

In [66]:
names

['muzammil', 'hutiya', 'hai', 'yasir', 'genious', 'hai', 'muzammil']

In [67]:
names = set(names)

In [68]:
names

{'genious', 'hai', 'hutiya', 'muzammil', 'yasir'}

In [69]:
students ={'yasir','muazmmil','talha'}

In [70]:
students

{'muazmmil', 'talha', 'yasir'}

In [71]:
arr = np.arange(15)

In [75]:
arr.reshape((5,-1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [76]:
arr = np.arange(15).reshape((5, 3))

In [77]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [84]:
flat=arr.flatten()

In [85]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [88]:
ravel = arr.ravel()

In [89]:
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [90]:
ravel

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [92]:
ravel[3:6] = 0

In [93]:
arr

array([[ 0,  1,  2],
       [ 0,  0,  0],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [99]:
flat[3:6]=0

In [100]:
arr

array([[ 0,  1,  2],
       [ 7,  7,  7],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])